# Generated by Django 3.0.6 on 2020-05-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PubgTournaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('map', models.CharField(max_length=200)),
                ('entryFees', models.CharField(max_length=200)),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('payMode', models.CharField(max_length=200)),
                ('furtherInfo', models.CharField(max_length=1000)),
            ],
        ),
    ]
